import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { ReactQueryClientProvider } from "./_providers/query-client-provider"
import { ToastProvider } from "./_providers/toast-provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClientProvider>
          <ToastProvider>
            <div className="text-4xl text-[#2d8cff] w-full text-center py-8">
              Welcome To &nbsp;
              <span className="text-[#2d8cff] font-semibold">Zoom</span>
            </div>
            {children}
          </ToastProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  )
}
